# Generated by Django 5.0.4 on 2024-06-25 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_amount", models.PositiveIntegerField(help_text="問題数")),
                (
                    "genre",
                    models.CharField(default="", help_text="????", max_length=1024),
                ),
                ("giftPurchaseDate", models.DateTimeField(help_text="プレゼント買う日")),
                ("giftGivingDate", models.DateTimeField(help_text="プレゼント贈る日")),
            ],
        ),
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("age", models.PositiveIntegerField(help_text="年齢")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        help_text="性別",
                        max_length=10,
                    ),
                ),
                ("relationship", models.CharField(help_text="関係", max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="gathering",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="gathering",
            name="host",
        ),
        migrations.RemoveField(
            model_name="participation",
            name="gathering",
        ),
        migrations.RemoveField(
            model_name="message",
            name="gathering",
        ),
        migrations.RemoveField(
            model_name="ownership",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="ownership",
            name="presenter",
        ),
        migrations.RemoveField(
            model_name="participation",
            name="participant",
        ),
        migrations.RemoveField(
            model_name="message",
            name="body",
        ),
        migrations.RemoveField(
            model_name="message",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.AddField(
            model_name="message",
            name="answer",
            field=models.CharField(
                default="", editable=False, help_text="gpt答え", max_length=1024
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="question",
            field=models.CharField(default="", help_text="問題", max_length=1024),
        ),
        migrations.AddField(
            model_name="message",
            name="project",
            field=models.ForeignKey(
                default=1,
                help_text="対話",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="message",
                to="app.project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="receiver",
            field=models.ForeignKey(
                help_text="受け取り手",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project",
                to="app.receiver",
            ),
        ),
        migrations.CreateModel(
            name="Hobbies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hobby", models.CharField(help_text="趣味", max_length=1024)),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="受け取り手",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hobbies",
                        to="app.receiver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GiftHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gift", models.CharField(help_text="プレゼント", max_length=1024)),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="受け取り手",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="giftHistory",
                        to="app.receiver",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Gathering",
        ),
        migrations.DeleteModel(
            name="Ownership",
        ),
        migrations.DeleteModel(
            name="Participation",
        ),
    ]
