# Generated by Django 5.0.4 on 2024-06-15 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField(help_text="年齢")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        help_text="性別",
                        max_length=10,
                    ),
                ),
                ("relationship", models.CharField(help_text="関係", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Hobbies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hobby", models.CharField(help_text="趣味", max_length=1024)),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="受け取り手",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hobbies",
                        to="app.receiver",
                    ),
                ),
            ],
        ),
    ]
