# Generated by Django 5.0.4 on 2024-06-15 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiver",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="GiftHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gift", models.CharField(help_text="プレゼント", max_length=1024)),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="受け取り手",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="giftHistory",
                        to="app.receiver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_amount", models.PositiveIntegerField(help_text="問題数")),
                (
                    "genre",
                    models.CharField(default="", help_text="????", max_length=1024),
                ),
                ("giftPurchaseDate", models.DateTimeField(help_text="プレゼント買う日")),
                ("giftGivingDate", models.DateTimeField(help_text="プレゼント贈る日")),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="受け取り手",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project",
                        to="app.receiver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(help_text="問題", max_length=1024)),
                (
                    "generate",
                    models.CharField(
                        default="", editable=False, help_text="gpt答え", max_length=1024
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="対話",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message",
                        to="app.project",
                    ),
                ),
            ],
        ),
    ]
