# Generated by Django 5.0.4 on 2024-06-15 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_receiver_id_gifthistory_project_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="generate",
            new_name="answer",
        ),
    ]
